apiVersion: v1 
kind: Pod 
metadata:
  name: mysql
  labels:
    app: mysql 

spec: 
  containers:
  - name: mysql 
    image: mysql:5
    env: 
    - name: MYSQL_ROOT_PASSWORD
      value: password
    - name: MYSQL_DATABASE
      value: fleetman 

--- 
apiVersion: v1
kind: Service     
metadata: 
  name: mysql-service

spec:
  type: ClusterIP
  selector:
      app: mysql
  
  ports:
  - name:  mysql-default-port
    port:  3306
    protocol: TCP

