
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "mongo-db"
    namespace: "default"
  spec: 
    selector: 
      matchLabels: 
        app: "mongo-db"
    replicas: 1
    strategy: 
      type: "RollingUpdate"
      rollingUpdate: 
        maxSurge: 1
        maxUnavailable: 1
    minReadySeconds: 5
    template: 
      metadata: 
        labels: 
          app: "mongo-db"
      spec: 
        containers: 
          - 
            name: mongo-db
            image: mongo:4.4.6
            imagePullPolicy: "Always"
            env: 
              - 
                name: "MONGO_INITDB_ROOT_USERNAME"
                valueFrom:
                  secretKeyRef:
                    name: mongodb-secret
                    key: mongo-root-username
                
              -
                name: "MONGO_INITDB_ROOT_PASSWORD"
                valueFrom:
                  secretKeyRef:
                    name: mongodb-secret
                    key: mongo-root-password
                
            ports: 
              - 
                containerPort: 27017
                name: "mongodb"
                
            volumeMounts: 
              - 
                name: "mongodb-persistent-storage"
                mountPath: "/data/db"
                
        volumes: 
          - 
            name: "mongodb-persistent-storage"
            persistentVolumeClaim: 
              claimName: "mongodb-pvc"