---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "mongo-db-service"
    namespace: "default"
    labels: 
      app: "mongo-db-service"
  spec: 
    ports: 
      - 
        port: 27017
        nodePort: 30332
    selector: 
      app: "mongo-db"